name: RichMan
main: com.outbacksmp.richman.RichManPlugin
version: 1.0.1
api-version: 1.21
author: Astronaut
depend: [Vault]
softdepend: [Essentials, PlaceholderAPI]

commands:
  richman:
    description: Rich Man challenge
    usage: /richman
    permission: richman.command
